##Customer Shopping Behaviour Analysis

##1. Project Overview

Objective:
Analyze customer shopping data to understand purchasing patterns, preferences, and factors influencing buying behaviour.

Key Questions

Which category do customers buy the most?

Which age group spends the most?

What payment method is most used?

Does season affect purchasing behaviour?

Which locations generate the most revenue?

1.Insert the dataset

In [10]:
import pandas as pd
df = pd.read_csv(r"C:\Users\dell\Downloads\customer_shopping_behavior.csv")

In [11]:
df.info

<bound method DataFrame.info of       Customer ID  Age  Gender Item Purchased     Category  \
0               1   55    Male         Blouse     Clothing
1               2   19    Male        Sweater     Clothing
2               3   50    Male          Jeans     Clothing
3               4   21    Male        Sandals     Footwear
4               5   45    Male         Blouse     Clothing
...           ...  ...     ...            ...          ...
3895         3896   40  Female         Hoodie     Clothing
3896         3897   52  Female       Backpack  Accessories
3897         3898   46  Female           Belt  Accessories
3898         3899   44  Female          Shoes     Footwear
3899         3900   52  Female        Handbag  Accessories

      Purchase Amount (USD)       Location Size      Color  Season  \
0                        53       Kentucky    L       Gray  Winter
1                        64          Maine    L     Maroon  Winter
2                        73  Massachusetts    S     Maroon  Spring
3                        90   Rhode Island    M     Maroon  Spring
4                        49         Oregon    M  Turquoise  Spring
...                     ...            ...  ...        ...     ...
3895                     28       Virginia    L  Turquoise  Summer
3896                     49           Iowa    L      White  Spring
3897                     33     New Jersey    L      Green  Spring
3898                     77      Minnesota    S      Brown  Summer
3899                     81     California    M      Beige  Spring

      Review Rating Subscription Status   Shipping Type Discount Applied  \
0               3.1                 Yes         Express              Yes
1               3.1                 Yes         Express              Yes
2               3.1                 Yes   Free Shipping              Yes
3               3.5                 Yes    Next Day Air              Yes
4               2.7                 Yes   Free Shipping              Yes
...             ...                 ...             ...              ...
3895            4.2                  No  2-Day Shipping               No
3896            4.5                  No    Store Pickup               No
3897            2.9                  No        Standard               No
3898            3.8                  No         Express               No
3899            3.1                  No    Store Pickup               No

     Promo Code Used  Previous Purchases Payment Method Frequency of Purchases
0                Yes                  14          Venmo            Fortnightly
1                Yes                   2           Cash            Fortnightly
2                Yes                  23    Credit Card                 Weekly
3                Yes                  49         PayPal                 Weekly
4                Yes                  31         PayPal               Annually
...              ...                 ...            ...                    ...
3895              No                  32          Venmo                 Weekly
3896              No                  41  Bank Transfer              Bi-Weekly
3897              No                  24          Venmo              Quarterly
3898              No                  24          Venmo                 Weekly
3899              No                  33          Venmo              Quarterly

[3900 rows x 18 columns]>

In [12]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [ ]:
df.describe(include='all')

In [ ]:
df.isna().sum()

In [ ]:
df['Category'].unique()

#fixing nulls

In [13]:
df['Review Rating']= df.groupby('Category')['Review Rating'].transform(lambda x:x.fillna(x.median()))

In [14]:
df['Review Rating'].isna().sum()

np.int64(0)

In [ ]:
df.columns

In [15]:
df.columns = df.columns.str.lower()

In [16]:
df.columns= df.columns.str.replace(' ','_')

In [17]:
df= df.rename(columns={'purchase_amount_(usd)':'purchase_amount'})

In [18]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [19]:
##create column age group

labels = ['young adult','adult','middleaged','senior']
df['age_group'] = pd.qcut(df['age'],4,labels=labels)

In [20]:
df[['age','age_group']].head(10)

   age    age_group
0   55   middleaged
1   19  young adult
2   50   middleaged
3   21  young adult
4   45   middleaged
5   46   middleaged
6   63       senior
7   27  young adult
8   26  young adult
9   57   middleaged

In [21]:
df[['discount_applied','promo_code_used']]

     discount_applied promo_code_used
0                 Yes             Yes
1                 Yes             Yes
2                 Yes             Yes
3                 Yes             Yes
4                 Yes             Yes
...               ...             ...
3895               No              No
3896               No              No
3897               No              No
3898               No              No
3899               No              No

[3900 rows x 2 columns]

In [25]:
(df['discount_applied']==df['promo_code_used']).all()

np.True_

In [22]:
df = df.drop('promo_code_used', axis=1)

In [23]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group'],
      dtype='object')

In [24]:
df['frequency_of_purchases'].head(20)

0     Fortnightly
1     Fortnightly
2          Weekly
3          Weekly
4        Annually
5          Weekly
6       Quarterly
7          Weekly
8        Annually
9       Quarterly
10      Bi-Weekly
11    Fortnightly
12    Fortnightly
13         Weekly
14         Weekly
15        Monthly
16      Bi-Weekly
17      Quarterly
18         Weekly
19      Bi-Weekly
Name: frequency_of_purchases, dtype: object

In [25]:
## create a column for purchase frequency days
frequency_mapping ={
'Fortnightly': 14,
 'Weekly': 7,
 'Bi-Weekly':14,
 'Monthly':30,
 'Quarterly': 90,
 'Annually':365,
 'Every 3 Months':90}
 
df['purchase_frequency_days'] =  df['frequency_of_purchases'].map(frequency_mapping)

In [26]:
df[['frequency_of_purchases','purchase_frequency_days']]

     frequency_of_purchases  purchase_frequency_days
0               Fortnightly                       14
1               Fortnightly                       14
2                    Weekly                        7
3                    Weekly                        7
4                  Annually                      365
...                     ...                      ...
3895                 Weekly                        7
3896              Bi-Weekly                       14
3897              Quarterly                       90
3898                 Weekly                        7
3899              Quarterly                       90

[3900 rows x 2 columns]

In [27]:
df['purchase_frequency_days'].dtype

dtype('int64')

In [28]:
df.isna().sum()

customer_id                0
age                        0
gender                     0
item_purchased             0
category                   0
purchase_amount            0
location                   0
size                       0
color                      0
season                     0
review_rating              0
subscription_status        0
shipping_type              0
discount_applied           0
previous_purchases         0
payment_method             0
frequency_of_purchases     0
age_group                  0
purchase_frequency_days    0
dtype: int64

In [29]:
df[['purchase_frequency_days','frequency_of_purchases']]

      purchase_frequency_days frequency_of_purchases
0                          14            Fortnightly
1                          14            Fortnightly
2                           7                 Weekly
3                           7                 Weekly
4                         365               Annually
...                       ...                    ...
3895                        7                 Weekly
3896                       14              Bi-Weekly
3897                       90              Quarterly
3898                        7                 Weekly
3899                       90              Quarterly

[3900 rows x 2 columns]

In [30]:
df['frequency_of_purchases'].unique()

array(['Fortnightly', 'Weekly', 'Annually', 'Quarterly', 'Bi-Weekly',
       'Monthly', 'Every 3 Months'], dtype=object)

In [31]:
import sqlalchemy
from sqlalchemy  import create_engine
engine = create_engine('postgresql+psycopg2://postgres:sqlwell@localhost:5432/Customer_behavior')

In [32]:
df.to_sql('customer',con=engine,if_exists='replace',index=False)

900